package com.example.nirogyamhealthathome

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.TextView

class RemedyApiActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_remedy_api)

        val symptomInput = findViewById<EditText>(R.id.symptomInput)
        val searchButton3 = findViewById<Button>(R.id.searchButton3)
        val remedyText = findViewById<TextView>(R.id.remedyText)

        searchButton3.setOnClickListener {
            val symptom = symptomInput.text.toString()
            val remedy = getRemedyForSymptom(symptom)
            remedyText.text = remedy
        }
    }

    private fun getRemedyForSymptom(symptom: String): String {
        // Replace this with your own logic to fetch remedy based on symptom
        // For simplicity, returning some hardcoded remedies for demonstration
        return when (symptom.lowercase()) {
            "cough" -> " Stay hydrated with warm fluids like herbal tea or broth. Use a humidifier or take a steamy shower to relieve congestion. Use cough drops or lozenges to soothe throat irritation. Avoid irritants like smoke or strong odors."
            "sore throat" -> "Gargle with warm salt water to reduce inflammation. Drink warm liquids like herbal tea with honey or broth. Use throat lozenges or hard candy to soothe throat irritation. Avoid irritants like smoke or strong odors."
            "runny nose" -> " Use saline nasal sprays or rinses to flush out mucus. Use a humidifier to add moisture to the air. Stay hydrated with plenty of fluids. Avoid known allergens or irritants."
            "nausea" -> " Eat small, bland meals like crackers, toast, or bananas. Sip clear fluids like water, ginger ale, or electrolyte solutions. Avoid spicy, greasy, or strong-smelling foods. Try ginger in various forms (ginger tea, ginger candies) to alleviate nausea."
            "vomiting" -> " Rest in a comfortable position. Start with clear fluids like water, broth, or electrolyte solutions. Gradually reintroduce bland foods like crackers, toast, or rice. Avoid eating large meals or foods that are difficult to digest."
            "diarrhea" -> "Stay hydrated with electrolyte solutions or clear fluids. Eat bland, easy-to-digest foods like bananas, rice, applesauce, or toast (BRAT diet). Avoid high-fiber, greasy, spicy, or dairy-containing foods. Use over-the-counter anti-diarrheal medication if necessary, but use with caution."
            "abdominal pain" -> "Apply a heating pad or warm compress to the affected area. Take over-the-counter pain relievers like acetaminophen or ibuprofen. Rest in a comfortable position and avoid strenuous activities. If pain persists or worsens, seek medical attention."
            "constipation" -> " Drink plenty of water and fluids throughout the day. Eat high-fiber foods like fruits, vegetables, whole grains, and legumes. Get regular exercise to promote bowel movements. Use over-the-counter laxatives or stool softeners if necessary, but use with caution. "
            "fatigue" -> " Ensure you're getting adequate sleep each night (7-9 hours for adults). Eat a balanced diet with plenty of fruits, vegetables, lean proteins, and whole grains. Stay hydrated by drinking plenty of water throughout the day. Engage in regular physical activity, even light exercise can help boost energy levels."
            "dizziness" -> " Sit or lie down in a comfortable position, preferably with your head slightly elevated. Drink water or other fluids to stay hydrated, as dehydration can worsen dizziness. Avoid sudden movements or changes in position, such as standing up quickly. If dizziness persists or is severe, seek medical attention, as it could be a sign of a more serious underlying condition."
          "headache" -> "Apply a cold compress (such as a cold pack or a cold washcloth) to the forehead or temples to constrict blood vessels and reduce inflammation. Alternatively, use a warm compress (such as a heating pad or a warm towel) to relax tense muscles and improve blood flow. Rest in a quiet, dark room to minimize sensory stimulation and promote relaxation. Consider over-the-counter pain relievers such as acetaminophen, ibuprofen, or aspirin, but use them according to the recommended dosage."
    "back pain" -> " Apply an ice pack wrapped in a towel to the affected area for about 15 minutes to reduce inflammation and numb the area. After icing, switch to a heat pack or a warm towel for about 20 minutes to relax muscles and improve blood flow. Rest in a comfortable position, avoiding activities that exacerbate the pain. Practice gentle stretching exercises to improve flexibility and relieve tension in the muscles of the back."
            "joint pain" -> "Apply ice or a cold pack wrapped in a towel to the affected joint for about 15-20 minutes to reduce swelling and numb the area. Alternatively, use a heating pad or warm towel to relax muscles and improve blood flow to the joint. Engage in gentle stretching exercises to improve joint flexibility and reduce stiffness. Consider taking over-the-counter pain relievers such as acetaminophen or ibuprofen to alleviate pain and inflammation, but follow the recommended dosage."
            "muscle cramps" -> "Immediately stop any activity that may have triggered the muscle cramp. Gently stretch and massage the affected muscle to relieve tension and promote relaxation. Apply a heating pad or warm towel to the cramped muscle to improve blood flow and relax the muscle fibers. Drink water or a sports drink containing electrolytes to rehydrate and replenish lost fluids and minerals."
             "chest pain" -> " Seek immediate medical attention if you experience chest pain, as it could be a sign of a heart attack or another serious medical condition. Rest in a comfortable position, avoiding strenuous activities that may worsen the pain. If the chest pain is accompanied by other symptoms such as shortness of breath, dizziness, or nausea, call emergency services immediately."
         "shortness of breath" -> "Sit upright in a comfortable chair or lie down with your head elevated to ease breathing. Practice deep breathing exercises, such as pursed-lip breathing or diaphragmatic breathing, to help expand your lungs and improve oxygen flow. If shortness of breath is severe or persistent, seek immediate medical attention, as it could be a sign of a serious respiratory or cardiovascular condition."
         "heartburn" -> " Avoid trigger foods and beverages that can exacerbate heartburn, such as spicy, fatty, or acidic foods, caffeine, and alcohol. Eat smaller, more frequent meals to prevent overloading your stomach and reduce the risk of acid reflux. Elevate the head of your bed by placing blocks or risers under the legs of the bed to keep your head higher than your stomach while sleeping."
         "indigestion"-> " Avoid trigger foods that can cause indigestion, such as fatty, greasy, spicy, or acidic foods, as well as carbonated beverages and caffeine. Eat smaller, more frequent meals to prevent overloading your digestive system and promote more efficient digestion. Avoid lying down or reclining immediately after eating, as this can increase the risk of acid reflux and indigestion."
        "stomach ache" -> " Apply a heating pad or warm compress to the abdomen to soothe muscle cramps and promote relaxation. Drink herbal tea such as peppermint or ginger tea, which can help ease stomach discomfort and reduce nausea. Avoid heavy or fatty meals that can exacerbate stomach ache and opt for lighter, easier-to-digest foods like broth-based soups, crackers, or plain rice."
        "rash" -> "  Apply calamine lotion or hydrocortisone cream to soothe itching and reduce inflammation. Take over-the-counter antihistamines such as diphenhydramine (Benadryl) to alleviate itching and reduce allergic reactions. Avoid scratching the rash to prevent further irritation, inflammation, and the risk of infection."
        "itching" -> "Apply a cool compress (such as a cold washcloth or ice pack wrapped in a towel) to the itchy area to numb the skin and reduce inflammation. Moisturize the skin with a gentle, fragrance-free moisturizer to soothe dryness and relieve itching. Avoid hot showers or baths, as hot water can further irritate the skin and worsen itching."
        "sunburn" -> "  Apply aloe vera gel or a soothing moisturizer containing aloe vera to the sunburned area to hydrate the skin and promote healing. Take cool baths or showers to soothe the skin and relieve discomfort. Drink plenty of water to stay hydrated and help the body recover from dehydration caused by sunburn."
        "bruising" -> "Apply a cold compress (such as a bag of frozen peas or a cold washcloth) to the bruised area for about 15-20 minutes to reduce swelling and numb the skin. Elevate the affected area above heart level, if possible, to reduce blood flow and minimize swelling. Rest and avoid activities that may exacerbate the bruising or cause further injury."
        "minor burns" -> "Immediately run the burned area under cool (not cold) running water for several minutes to reduce pain, swelling, and further damage to the skin. Apply a thin layer of antibiotic ointment (such as bacitracin or polysporin) to the burned area to prevent infection and promote healing. Cover the burned area with a sterile nonstick bandage or gauze pad to protect it from further irritation and keep it clean."
        "minor cuts" -> " Clean the cut with mild soap and water to remove dirt, debris, and bacteria from the wound. Apply a thin layer of antibiotic ointment to the cut to prevent infection and promote healing. Cover the cut with a sterile adhesive bandage or gauze pad to protect it from further injury and keep it clean."
        "splinter" -> "Use clean tweezers to carefully remove the splinter from the skin, pulling it out in the same direction it entered. Clean the area with mild soap and water to remove any dirt or debris. Apply a thin layer of antibiotic ointment to the area to prevent infection. Cover the area with a sterile adhesive bandage or gauze pad to protect it from further injury and keep it clean."
        "toothache"  -> "Rinse your mouth with warm salt water to help reduce pain and inflammation. Apply a cold compress (such as a cold washcloth or ice pack wrapped in a towel) to the outside of your cheek to numb the area and reduce swelling. Take over-the-counter pain relievers such as ibuprofen (Advil, Motrin) or acetaminophen (Tylenol) to alleviate pain and reduce inflammation."
        "gum pain" -> "Rinse your mouth with warm salt water to help reduce pain and inflammation. Avoid hard or crunchy foods that may aggravate gum pain and cause further irritation. Use a soft-bristled toothbrush and gentle brushing techniques to clean your teeth and gums without causing additional discomfort."
        "earache" -> "  Apply a warm compress (such as a warm washcloth or heating pad) to the affected ear to help relieve pain and reduce inflammation. Take over-the-counter pain relievers such as ibuprofen (Advil, Motrin) or acetaminophen (Tylenol) to alleviate pain and reduce fever, if present. Avoid inserting objects into the ear canal, as this can cause further irritation or injury. These remedies can provide relief for mild to moderate symptoms, but it is important to consult a healthcare professional if symptoms persist or worsen, or if you experience severe or concerning symptoms."
        "eye irritation" -> " Rinse the affected eye with cool, clean water to flush out any irritants or foreign particles. Use artificial tears or lubricating eye drops to help relieve dryness and soothe irritation. Avoid rubbing your eyes, as this can exacerbate irritation and potentially cause further damage to the delicate tissues."
        "pink eye (conjunctivitis)" -> "Apply a warm compress (a clean, damp washcloth warmed in hot water) to the affected eye to help soothe discomfort and reduce inflammation. Avoid touching or rubbing your eyes, as this can spread the infection to other people or other parts of your own body. Wash your hands frequently with soap and water, especially after touching your eyes or face, to prevent the spread of infection."
        "sinus pain" -> " Use a saline nasal spray or nasal irrigation system to help flush out mucus and relieve congestion in the sinuses. Apply a warm compress (a warm, damp towel or washcloth) to the face over the sinus area to help reduce pain and pressure. Stay hydrated by drinking plenty of fluids, such as water, herbal tea, or clear broth, to help thin mucus and keep nasal passages moist."
         "menstrual cramps" -> " Apply a heating pad or warm compress to the lower abdomen to help relax muscles and alleviate cramping. Take over-the-counter pain relievers such as ibuprofen (Advil, Motrin) or naproxen (Aleve) to help reduce pain and inflammation. Rest in a comfortable position and practice relaxation techniques such as deep breathing or meditation to help relieve stress and tension in the body."
        " menstrual bloating" -> " Drink plenty of water to help flush out excess fluids and reduce bloating. Avoid salty or high-sodium foods, which can contribute to water retention and exacerbate bloating. Engage in gentle exercise such as walking or yoga to help stimulate digestion and reduce bloating."
      "menstrual headache" -> " Apply a cold compress (a cold pack or cold washcloth) to the forehead or temples to help constrict blood vessels and reduce headache pain. Rest in a quiet, dark room to minimize sensory stimulation and promote relaxation. Stay hydrated by drinking plenty of water to help alleviate dehydration, which can contribute to headaches."
      "menstrual mood swings" -> "Practice relaxation techniques such as deep breathing, meditation, or progressive muscle relaxation to help reduce stress and anxiety. Get regular exercise, such as walking, jogging, or yoga, to help improve mood and reduce symptoms of depression and anxiety. Maintain a balanced diet rich in fruits, vegetables, whole grains, lean proteins, and healthy fats to support overall physical and mental health."
      "menstrual fatigue" -> " Ensure you're getting adequate sleep each night (7-9 hours for adults) to help combat fatigue and promote overall health and well-being. Eat a balanced diet with plenty of fruits, vegetables, whole grains, and lean proteins to provide your body with the nutrients it needs to function optimally. Stay hydrated by drinking plenty of water throughout the day to help prevent dehydration, which can contribute to feelings of fatigue."
      "menstrual nausea"-> "Eat small, frequent meals throughout the day to help prevent nausea and maintain stable blood sugar levels. Stay hydrated by drinking plenty of fluids, such as water, herbal tea, or clear broth, to help prevent dehydration and alleviate nausea. Avoid trigger foods that may exacerbate nausea, such as spicy, greasy, or acidic foods, and opt for bland, easily digestible foods instead."
      "menstrual diarrhea"-> " Stay hydrated with electrolyte solutions such as sports drinks or oral rehydration solutions to help replace lost fluids and electrolytes. Eat bland, easily digestible foods such as bananas, rice, applesauce, or toast (BRAT diet) to help firm up stools and alleviate diarrhea. Rest in a comfortable position and avoid strenuous activities to help conserve energy and promote recovery."
      "anxiety" -> " Practice deep breathing exercises such as diaphragmatic breathing or 4-7-8 breathing to help calm the nervous system and reduce anxiety. Engage in relaxation techniques such as progressive muscle relaxation, guided imagery, or mindfulness meditation to promote relaxation and stress relief. Talk to a friend, family member, or counselor about your feelings and concerns to gain perspective and emotional support."
      "depression" ->" Engage in regular physical activity such as walking, jogging, swimming, or yoga to help boost mood and reduce symptoms of depression. Seek social support from friends, family members, or support groups to help alleviate feelings of loneliness and isolation. Talk to a therapist or counselor to explore underlying issues, learn coping strategies, and develop a treatment plan tailored to your needs."
      "stress" -> "Practice mindfulness meditation or deep breathing exercises to help reduce stress and promote relaxation. Engage in hobbies or activities that you enjoy and find fulfilling, such as reading, gardening, painting, or playing music, to help distract from stressors and improve mood. Get regular exercise, such as walking, cycling, or dancing, to help release tension, boost endorphins, and improve overall well-being."
      "insomnia" -> "  Maintain a regular sleep schedule by going to bed and waking up at the same time each day, even on weekends. Avoid caffeine and stimulants in the hours leading up to bedtime, as they can interfere with sleep. Create a relaxing bedtime routine that includes activities such as reading, taking a warm bath, or practicing relaxation techniques to signal to your body that it's time to wind down."
      "panic attacks" -> "Practice deep breathing exercises such as diaphragmatic breathing or box breathing to help calm the body and reduce symptoms of panic. Use grounding techniques such as focusing on your senses (sight, sound, touch, smell, taste) or repeating a calming phrase to help bring your attention back to the present moment. Seek professional help from a therapist or psychiatrist if panic attacks are severe or frequent, as they can provide therapy, medication, and support to help manage symptoms."
      "acne" -> " Wash your face twice daily with a gentle cleanser to remove dirt, oil, and bacteria without stripping the skin of its natural oils. Apply topical acne treatments containing ingredients such as benzoyl peroxide, salicylic acid, or retinoids to help unclog pores, reduce inflammation, and prevent breakouts. Avoid picking, squeezing, or popping pimples, as this can lead to scarring and further inflammation."
      "hair loss" -> " Eat a balanced diet rich in vitamins, minerals, and nutrients such as protein, iron, and biotin to support healthy hair growth. Avoid harsh hair treatments such as chemical dyes, bleaches, or perms that can damage the hair and contribute to hair loss. Use gentle hair care products free of sulfates, parabens, and other harsh chemicals that can strip the hair of its natural oils and contribute to hair loss."
      "dandruff" -> " Use an anti-dandruff shampoo containing ingredients such as zinc pyrithione, selenium sulfide, or ketoconazole to help reduce flakiness and control dandruff. Avoid scratching or picking at the scalp, as this can worsen dandruff and lead to irritation. Maintain good hygiene by washing your hair regularly and keeping the scalp clean and moisturized to help prevent dandruff."
      "bad breath" -> " Brush your teeth and tongue twice daily with fluoride toothpaste to remove plaque, bacteria, and food particles that can contribute to bad breath. Floss between teeth daily to remove plaque and food debris from hard-to-reach areas. Use an alcohol-free mouthwash containing antibacterial ingredients such as chlorhexidine or cetylpyridinium chloride to help kill odor-causing bacteria and freshen breath."
      "body odor" -> "  Shower daily with warm water and soap to cleanse the skin and remove sweat, bacteria, and odor-causing substances. Wear breathable fabrics such as cotton or moisture-wicking materials that allow air to circulate and sweat to evaporate, reducing the likelihood of body odor. Use an antiperspirant or deodorant containing aluminum-based compounds to help reduce sweat production and mask odor throughout the day."


            else -> "No remedy found for this symptom."
        }
    }
}